SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EngineerLoginLog](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[EngineerId] [bigint] NOT NULL,
	[Platform] [tinyint] NOT NULL,
	[Stamp] [datetime] NOT NULL,
 CONSTRAINT [PK_EngineerLoginLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EngineerLoginLog] ADD  DEFAULT ('19010101') FOR [Stamp]
GO